/**
 * Multi-Agent Ecosystem Catalog
 * 62 Specialized Quantitative & Autonomous Agents across 6 Functional Divisions.
 */

import { AgentDefinition } from '../../src/types/quant';

export const INITIAL_AGENTS: AgentDefinition[] = [
  // 1. EXECUTIVE AGENTS (1-7)
  {
    id: 'EXEC-01',
    name: 'CEO / Supervisor Agent',
    role: 'Autonomous organization executive orchestration and governance',
    category: 'EXECUTIVE',
    reputationScore: 96,
    calibrationScore: 0.94,
    winRateContribution: 58.4,
    pnlContributionUsd: 14.8,
    status: 'ACTIVE',
    currentRegimeEffectiveness: { TREND_UP: 0.92, RANGE: 0.88, CRISIS: 0.95 },
    lastDeliberation: 'Prioritizing capital preservation and strict $100 baseline enforcement.',
  },
  {
    id: 'EXEC-02',
    name: 'Chief Quant Agent',
    role: 'Mathematical formulation, factor modeling, and statistical rigor',
    category: 'EXECUTIVE',
    reputationScore: 94,
    calibrationScore: 0.91,
    winRateContribution: 56.8,
    pnlContributionUsd: 12.4,
    status: 'ACTIVE',
    currentRegimeEffectiveness: { TREND_UP: 0.89, RANGE: 0.91, MEAN_REVERSION: 0.94 },
    lastDeliberation: 'Confirmed stationarity and Hurst exponent metrics across 50-bar rolling window.',
  },
  {
    id: 'EXEC-03',
    name: 'Chief AI Agent',
    role: 'Deep learning architectures, transformer ensembles, and uncertainty calibration',
    category: 'EXECUTIVE',
    reputationScore: 92,
    calibrationScore: 0.89,
    winRateContribution: 55.2,
    pnlContributionUsd: 9.6,
    status: 'ACTIVE',
    currentRegimeEffectiveness: { TREND_UP: 0.86, HIGH_VOLATILITY: 0.84 },
    lastDeliberation: 'Monitored ensemble prediction entropy; confidence within acceptable variance.',
  },
  {
    id: 'EXEC-04',
    name: 'Chief Risk Agent',
    role: 'Deterministic firewall supervision, drawdown limits, and veto authority',
    category: 'EXECUTIVE',
    reputationScore: 99,
    calibrationScore: 0.98,
    winRateContribution: 64.2,
    pnlContributionUsd: 22.1,
    status: 'ACTIVE',
    currentRegimeEffectiveness: { CRISIS: 0.99, HIGH_VOLATILITY: 0.97, RANGE: 0.92 },
    lastDeliberation: 'Enforcing $25 maximum position size and 1.5% max risk per trade.',
  },
  {
    id: 'EXEC-05',
    name: 'Chief Portfolio Agent',
    role: 'Risk parity weighting, CVaR optimization, and dynamic asset allocation',
    category: 'EXECUTIVE',
    reputationScore: 91,
    calibrationScore: 0.88,
    winRateContribution: 54.0,
    pnlContributionUsd: 8.5,
    status: 'ACTIVE',
    currentRegimeEffectiveness: { RANGE: 0.9, TREND_UP: 0.88 },
    lastDeliberation: 'Maintaining portfolio cash buffer at 65% for margin safety.',
  },
  {
    id: 'EXEC-06',
    name: 'Chief Technology Agent',
    role: 'IPC latency optimization, compute governor, and WebSocket pipelines',
    category: 'EXECUTIVE',
    reputationScore: 95,
    calibrationScore: 0.92,
    winRateContribution: 52.0,
    pnlContributionUsd: 4.2,
    status: 'ACTIVE',
    currentRegimeEffectiveness: { ALL: 0.95 },
    lastDeliberation: 'All event-loop latency benchmarks below 15ms.',
  },
  {
    id: 'EXEC-07',
    name: 'Security Agent',
    role: 'Zero-trust credential encryption, API key sanitization, and tamper defense',
    category: 'EXECUTIVE',
    reputationScore: 99,
    calibrationScore: 0.99,
    winRateContribution: 50.0,
    pnlContributionUsd: 0.0,
    status: 'ACTIVE',
    currentRegimeEffectiveness: { ALL: 0.99 },
    lastDeliberation: 'Zero plain-text credentials in logs or payloads verified.',
  },

  // 2. MARKET INTELLIGENCE (8-24)
  { id: 'MKT-08', name: 'Real-Time Market Agent', role: 'Sub-millisecond tick ingestion and book processing', category: 'MARKET_INTELLIGENCE', reputationScore: 93, calibrationScore: 0.91, winRateContribution: 53.0, pnlContributionUsd: 6.2, status: 'ACTIVE', currentRegimeEffectiveness: { ALL: 0.92 } },
  { id: 'MKT-09', name: 'Historical Data Agent', role: 'Purged candle dataset retrieval and chronological alignment', category: 'MARKET_INTELLIGENCE', reputationScore: 94, calibrationScore: 0.95, winRateContribution: 52.5, pnlContributionUsd: 5.1, status: 'ACTIVE', currentRegimeEffectiveness: { ALL: 0.94 } },
  { id: 'MKT-10', name: 'Market Structure Agent', role: 'Support/resistance identification and liquidity pools', category: 'MARKET_INTELLIGENCE', reputationScore: 88, calibrationScore: 0.84, winRateContribution: 54.2, pnlContributionUsd: 7.8, status: 'ACTIVE', currentRegimeEffectiveness: { RANGE: 0.89, TREND_UP: 0.86 } },
  { id: 'MKT-11', name: 'Market Microstructure Agent', role: 'Spread dynamics, effective tick size, and queue position', category: 'MARKET_INTELLIGENCE', reputationScore: 91, calibrationScore: 0.89, winRateContribution: 55.0, pnlContributionUsd: 8.2, status: 'ACTIVE', currentRegimeEffectiveness: { HIGH_VOLATILITY: 0.91 } },
  { id: 'MKT-12', name: 'Order Book Agent', role: 'Level-2 depth imbalance and bid-ask volume delta', category: 'MARKET_INTELLIGENCE', reputationScore: 89, calibrationScore: 0.86, winRateContribution: 53.8, pnlContributionUsd: 7.1, status: 'ACTIVE', currentRegimeEffectiveness: { MOMENTUM: 0.88 } },
  { id: 'MKT-13', name: 'Liquidity Agent', role: 'Available depth, market impact forecasting, and slippage curves', category: 'MARKET_INTELLIGENCE', reputationScore: 92, calibrationScore: 0.9, winRateContribution: 56.1, pnlContributionUsd: 9.3, status: 'ACTIVE', currentRegimeEffectiveness: { LIQUIDITY_STRESS: 0.96 } },
  { id: 'MKT-14', name: 'Volatility Agent', role: 'Parkinson, Garman-Klass, and implied volatility tracking', category: 'MARKET_INTELLIGENCE', reputationScore: 90, calibrationScore: 0.87, winRateContribution: 54.6, pnlContributionUsd: 8.0, status: 'ACTIVE', currentRegimeEffectiveness: { HIGH_VOLATILITY: 0.93 } },
  { id: 'MKT-15', name: 'Regime Detection Agent', role: 'HMM and statistical transition classification', category: 'MARKET_INTELLIGENCE', reputationScore: 95, calibrationScore: 0.93, winRateContribution: 59.2, pnlContributionUsd: 13.5, status: 'ACTIVE', currentRegimeEffectiveness: { ALL: 0.94 } },
  { id: 'MKT-16', name: 'Correlation Agent', role: 'Multi-asset covariance matrices and decorrelation alarms', category: 'MARKET_INTELLIGENCE', reputationScore: 87, calibrationScore: 0.83, winRateContribution: 51.5, pnlContributionUsd: 4.8, status: 'ACTIVE', currentRegimeEffectiveness: { CRISIS: 0.91 } },
  { id: 'MKT-17', name: 'Cross-Asset Agent', role: 'FX, indices, and crypto lead-lag relationship analysis', category: 'MARKET_INTELLIGENCE', reputationScore: 86, calibrationScore: 0.82, winRateContribution: 52.1, pnlContributionUsd: 5.4, status: 'ACTIVE', currentRegimeEffectiveness: { TREND_UP: 0.85 } },
  { id: 'MKT-18', name: 'Macro Agent', role: 'Central bank rates, inflation releases, and liquidity cycles', category: 'MARKET_INTELLIGENCE', reputationScore: 85, calibrationScore: 0.8, winRateContribution: 50.8, pnlContributionUsd: 3.9, status: 'ACTIVE', currentRegimeEffectiveness: { CRISIS: 0.88 } },
  { id: 'MKT-19', name: 'News Agent', role: 'High-speed headline impact classification', category: 'MARKET_INTELLIGENCE', reputationScore: 83, calibrationScore: 0.79, winRateContribution: 51.0, pnlContributionUsd: 4.1, status: 'ACTIVE', currentRegimeEffectiveness: { HIGH_VOLATILITY: 0.84 } },
  { id: 'MKT-20', name: 'Sentiment Agent', role: 'On-chain, social sentiment, and funding rate positioning', category: 'MARKET_INTELLIGENCE', reputationScore: 81, calibrationScore: 0.76, winRateContribution: 49.5, pnlContributionUsd: 2.5, status: 'STANDBY', currentRegimeEffectiveness: { MOMENTUM: 0.82 } },
  { id: 'MKT-21', name: 'Event Risk Agent', role: 'Earnings, CPI, FOMC, and rollover blackout gatekeeper', category: 'MARKET_INTELLIGENCE', reputationScore: 97, calibrationScore: 0.96, winRateContribution: 62.0, pnlContributionUsd: 18.0, status: 'ACTIVE', currentRegimeEffectiveness: { CRISIS: 0.98 } },
  { id: 'MKT-22', name: 'Crypto Intelligence Agent', role: 'On-chain whale transfers, gas fees, and DEX volumes', category: 'MARKET_INTELLIGENCE', reputationScore: 88, calibrationScore: 0.85, winRateContribution: 53.5, pnlContributionUsd: 6.9, status: 'ACTIVE', currentRegimeEffectiveness: { TREND_UP: 0.87 } },
  { id: 'MKT-23', name: 'Funding/Basis Agent', role: 'Perpetual funding rate arbitrage and term basis tracking', category: 'MARKET_INTELLIGENCE', reputationScore: 92, calibrationScore: 0.91, winRateContribution: 57.0, pnlContributionUsd: 11.2, status: 'ACTIVE', currentRegimeEffectiveness: { RANGE: 0.93 } },
  { id: 'MKT-24', name: 'Anomaly Detection Agent', role: 'Fat-tail spikes, flash crash alerts, and bad tick filtering', category: 'MARKET_INTELLIGENCE', reputationScore: 96, calibrationScore: 0.95, winRateContribution: 61.0, pnlContributionUsd: 16.4, status: 'ACTIVE', currentRegimeEffectiveness: { CRISIS: 0.97 } },

  // 3. STRATEGY LAB (25-37)
  { id: 'STRAT-25', name: 'Quant Research Agent', role: 'Formulates mathematical trading hypotheses', category: 'STRATEGY_LAB', reputationScore: 91, calibrationScore: 0.88, winRateContribution: 55.4, pnlContributionUsd: 9.8, status: 'ACTIVE', currentRegimeEffectiveness: { ALL: 0.9 } },
  { id: 'STRAT-26', name: 'Alpha Discovery Agent', role: 'Evolutionary formula mining and genetic symbolic search', category: 'STRATEGY_LAB', reputationScore: 89, calibrationScore: 0.86, winRateContribution: 54.0, pnlContributionUsd: 8.3, status: 'ACTIVE', currentRegimeEffectiveness: { MOMENTUM: 0.88 } },
  { id: 'STRAT-27', name: 'Trend Agent', role: 'Multi-timeframe trend continuation systems', category: 'STRATEGY_LAB', reputationScore: 90, calibrationScore: 0.87, winRateContribution: 56.2, pnlContributionUsd: 10.5, status: 'ACTIVE', currentRegimeEffectiveness: { TREND_UP: 0.94, TREND_DOWN: 0.92 } },
  { id: 'STRAT-28', name: 'Momentum Agent', role: 'Cross-sectional and time-series momentum factors', category: 'STRATEGY_LAB', reputationScore: 88, calibrationScore: 0.85, winRateContribution: 53.7, pnlContributionUsd: 7.9, status: 'ACTIVE', currentRegimeEffectiveness: { MOMENTUM: 0.9 } },
  { id: 'STRAT-29', name: 'Mean-Reversion Agent', role: 'Ornstein-Uhlenbeck and Bollinger mean reversion', category: 'STRATEGY_LAB', reputationScore: 92, calibrationScore: 0.9, winRateContribution: 57.5, pnlContributionUsd: 11.6, status: 'ACTIVE', currentRegimeEffectiveness: { RANGE: 0.95, MEAN_REVERSION: 0.96 } },
  { id: 'STRAT-30', name: 'Breakout Agent', role: 'Donchian and volatility expansion breakout signals', category: 'STRATEGY_LAB', reputationScore: 87, calibrationScore: 0.84, winRateContribution: 52.8, pnlContributionUsd: 6.8, status: 'ACTIVE', currentRegimeEffectiveness: { HIGH_VOLATILITY: 0.89 } },
  { id: 'STRAT-31', name: 'Statistical Arbitrage Agent', role: 'Cointegrated basket and residual spread trading', category: 'STRATEGY_LAB', reputationScore: 93, calibrationScore: 0.92, winRateContribution: 58.0, pnlContributionUsd: 12.8, status: 'ACTIVE', currentRegimeEffectiveness: { RANGE: 0.94 } },
  { id: 'STRAT-32', name: 'Pairs Trading Agent', role: 'Johansen cointegration and dynamic hedge ratios', category: 'STRATEGY_LAB', reputationScore: 91, calibrationScore: 0.89, winRateContribution: 56.4, pnlContributionUsd: 10.2, status: 'ACTIVE', currentRegimeEffectiveness: { RANGE: 0.92 } },
  { id: 'STRAT-33', name: 'Volatility Strategy Agent', role: 'Straddle replication, gamma scalping, and vol surface', category: 'STRATEGY_LAB', reputationScore: 86, calibrationScore: 0.82, winRateContribution: 51.2, pnlContributionUsd: 5.1, status: 'ACTIVE', currentRegimeEffectiveness: { HIGH_VOLATILITY: 0.88 } },
  { id: 'STRAT-34', name: 'Cross-Asset Strategy Agent', role: 'Lead-lag equity/FX/commodity spillover execution', category: 'STRATEGY_LAB', reputationScore: 85, calibrationScore: 0.81, winRateContribution: 50.9, pnlContributionUsd: 4.6, status: 'ACTIVE', currentRegimeEffectiveness: { TREND_UP: 0.84 } },
  { id: 'STRAT-35', name: 'Execution Strategy Agent', role: 'TWAP, VWAP, iceberg slicing, and passive fill placement', category: 'STRATEGY_LAB', reputationScore: 94, calibrationScore: 0.93, winRateContribution: 58.8, pnlContributionUsd: 13.9, status: 'ACTIVE', currentRegimeEffectiveness: { ALL: 0.93 } },
  { id: 'STRAT-36', name: 'Strategy Evolution Agent', role: 'Genetic parameter crossover and mutation scheduler', category: 'STRATEGY_LAB', reputationScore: 89, calibrationScore: 0.86, winRateContribution: 54.1, pnlContributionUsd: 8.0, status: 'ACTIVE', currentRegimeEffectiveness: { ALL: 0.88 } },
  { id: 'STRAT-37', name: 'Strategy Critic Agent', role: 'Hostile adversarial review disproving overfitted backtests', category: 'STRATEGY_LAB', reputationScore: 98, calibrationScore: 0.97, winRateContribution: 63.5, pnlContributionUsd: 21.0, status: 'ACTIVE', currentRegimeEffectiveness: { ALL: 0.97 } },

  // 4. AI LAB (38-49)
  { id: 'AI-38', name: 'Feature Engineering Agent', role: 'Stationary feature transformation and scaling without leakage', category: 'AI_LAB', reputationScore: 93, calibrationScore: 0.92, winRateContribution: 56.0, pnlContributionUsd: 10.0, status: 'ACTIVE', currentRegimeEffectiveness: { ALL: 0.93 } },
  { id: 'AI-39', name: 'Feature Discovery Agent', role: 'Mutual information and SHAP factor importance analysis', category: 'AI_LAB', reputationScore: 90, calibrationScore: 0.88, winRateContribution: 54.2, pnlContributionUsd: 8.5, status: 'ACTIVE', currentRegimeEffectiveness: { ALL: 0.9 } },
  { id: 'AI-40', name: 'Supervised ML Agent', role: 'LightGBM and CatBoost gradient boosted tree models', category: 'AI_LAB', reputationScore: 92, calibrationScore: 0.9, winRateContribution: 56.8, pnlContributionUsd: 11.0, status: 'ACTIVE', currentRegimeEffectiveness: { TREND_UP: 0.91, RANGE: 0.92 } },
  { id: 'AI-41', name: 'Deep Learning Agent', role: 'Residual convolutional and multi-head temporal networks', category: 'AI_LAB', reputationScore: 89, calibrationScore: 0.86, winRateContribution: 53.9, pnlContributionUsd: 7.7, status: 'ACTIVE', currentRegimeEffectiveness: { MOMENTUM: 0.88 } },
  { id: 'AI-42', name: 'Time-Series Agent', role: 'ARIMA, GARCH, and state space parameter estimation', category: 'AI_LAB', reputationScore: 91, calibrationScore: 0.89, winRateContribution: 55.5, pnlContributionUsd: 9.3, status: 'ACTIVE', currentRegimeEffectiveness: { MEAN_REVERSION: 0.92 } },
  { id: 'AI-43', name: 'Transformer Agent', role: 'Temporal Fusion Transformer with attention mechanisms', category: 'AI_LAB', reputationScore: 91, calibrationScore: 0.88, winRateContribution: 55.1, pnlContributionUsd: 8.9, status: 'ACTIVE', currentRegimeEffectiveness: { TREND_UP: 0.9 } },
  { id: 'AI-44', name: 'Probabilistic Forecasting Agent', role: 'Quantile loss forecasting (P10, P50, P90 return bands)', category: 'AI_LAB', reputationScore: 94, calibrationScore: 0.93, winRateContribution: 58.2, pnlContributionUsd: 13.0, status: 'ACTIVE', currentRegimeEffectiveness: { ALL: 0.93 } },
  { id: 'AI-45', name: 'Uncertainty Agent', role: 'Epistemic and aleatoric uncertainty scoring', category: 'AI_LAB', reputationScore: 96, calibrationScore: 0.95, winRateContribution: 60.8, pnlContributionUsd: 17.2, status: 'ACTIVE', currentRegimeEffectiveness: { CRISIS: 0.98, HIGH_VOLATILITY: 0.95 } },
  { id: 'AI-46', name: 'Ensemble Agent', role: 'Mixture of Experts (MoE) gating network', category: 'AI_LAB', reputationScore: 93, calibrationScore: 0.91, winRateContribution: 57.0, pnlContributionUsd: 11.8, status: 'ACTIVE', currentRegimeEffectiveness: { ALL: 0.92 } },
  { id: 'AI-47', name: 'Model Selection Agent', role: 'OOS validation metrics and AIC/BIC model pruning', category: 'AI_LAB', reputationScore: 92, calibrationScore: 0.9, winRateContribution: 56.1, pnlContributionUsd: 10.4, status: 'ACTIVE', currentRegimeEffectiveness: { ALL: 0.91 } },
  { id: 'AI-48', name: 'Model Validation Agent', role: 'Combinatorial Purged Cross-Validation (CPCV)', category: 'AI_LAB', reputationScore: 95, calibrationScore: 0.94, winRateContribution: 59.5, pnlContributionUsd: 15.0, status: 'ACTIVE', currentRegimeEffectiveness: { ALL: 0.95 } },
  { id: 'AI-49', name: 'Meta-Learning Agent', role: 'Fast regime adaptation and hyperparameter meta-tuning', category: 'AI_LAB', reputationScore: 88, calibrationScore: 0.85, winRateContribution: 53.4, pnlContributionUsd: 7.2, status: 'ACTIVE', currentRegimeEffectiveness: { TRANSITION: 0.89 } },

  // 5. RL LAB (50-55)
  { id: 'RL-50', name: 'RL Research Agent', role: 'Formulates MDP reward functions and state space dynamics', category: 'RL_LAB', reputationScore: 89, calibrationScore: 0.86, winRateContribution: 54.0, pnlContributionUsd: 7.9, status: 'ACTIVE', currentRegimeEffectiveness: { ALL: 0.88 } },
  { id: 'RL-51', name: 'Execution RL Agent', role: 'PPO-based micro-order submission optimizing implementation shortfall', category: 'RL_LAB', reputationScore: 92, calibrationScore: 0.9, winRateContribution: 57.1, pnlContributionUsd: 11.5, status: 'ACTIVE', currentRegimeEffectiveness: { ALL: 0.92 } },
  { id: 'RL-52', name: 'Portfolio RL Agent', role: 'Deep Q-Network for dynamic leverage and asset rebalancing', category: 'RL_LAB', reputationScore: 90, calibrationScore: 0.87, winRateContribution: 55.0, pnlContributionUsd: 9.1, status: 'ACTIVE', currentRegimeEffectiveness: { RANGE: 0.91 } },
  { id: 'RL-53', name: 'Position Sizing RL Agent', role: 'Adaptive fractional Kelly policy under volatility regime shifts', category: 'RL_LAB', reputationScore: 93, calibrationScore: 0.91, winRateContribution: 58.0, pnlContributionUsd: 12.6, status: 'ACTIVE', currentRegimeEffectiveness: { ALL: 0.93 } },
  { id: 'RL-54', name: 'Regime Policy Agent', role: 'Soft Actor-Critic (SAC) multi-task regime policy selector', category: 'RL_LAB', reputationScore: 91, calibrationScore: 0.89, winRateContribution: 56.3, pnlContributionUsd: 10.7, status: 'ACTIVE', currentRegimeEffectiveness: { TRANSITION: 0.92 } },
  { id: 'RL-55', name: 'RL Evaluation Agent', role: 'Offline off-policy evaluation preventing simulation-to-reality collapse', category: 'RL_LAB', reputationScore: 96, calibrationScore: 0.95, winRateContribution: 61.2, pnlContributionUsd: 17.5, status: 'ACTIVE', currentRegimeEffectiveness: { ALL: 0.96 } },

  // 6. OPERATIONS (56-62)
  { id: 'OPS-56', name: 'Execution Agent', role: 'Deterministic order routing, broker acknowledgment, and fill tracking', category: 'OPERATIONS', reputationScore: 98, calibrationScore: 0.98, winRateContribution: 62.8, pnlContributionUsd: 20.1, status: 'ACTIVE', currentRegimeEffectiveness: { ALL: 0.98 } },
  { id: 'OPS-57', name: 'Reconciliation Agent', role: 'Real-time ledger audit comparing local state to exchange balances', category: 'OPERATIONS', reputationScore: 99, calibrationScore: 0.99, winRateContribution: 65.0, pnlContributionUsd: 23.5, status: 'ACTIVE', currentRegimeEffectiveness: { ALL: 0.99 } },
  { id: 'OPS-58', name: 'Monitoring Agent', role: 'Telemetry, tick-to-trade latency, and resource consumption health', category: 'OPERATIONS', reputationScore: 97, calibrationScore: 0.97, winRateContribution: 60.0, pnlContributionUsd: 16.0, status: 'ACTIVE', currentRegimeEffectiveness: { ALL: 0.97 } },
  { id: 'OPS-59', name: 'Incident Response Agent', role: 'Autonomous circuit-breaker activation and failover management', category: 'OPERATIONS', reputationScore: 99, calibrationScore: 0.99, winRateContribution: 66.0, pnlContributionUsd: 25.0, status: 'ACTIVE', currentRegimeEffectiveness: { CRISIS: 0.99 } },
  { id: 'OPS-60', name: 'Data Quality Agent', role: 'Gap detection, stale price detection, and payload schema validator', category: 'OPERATIONS', reputationScore: 98, calibrationScore: 0.98, winRateContribution: 63.0, pnlContributionUsd: 20.8, status: 'ACTIVE', currentRegimeEffectiveness: { ALL: 0.98 } },
  { id: 'OPS-61', name: 'Drift Detection Agent', role: 'Population Stability Index (PSI) and concept drift watchdog', category: 'OPERATIONS', reputationScore: 95, calibrationScore: 0.94, winRateContribution: 59.0, pnlContributionUsd: 14.5, status: 'ACTIVE', currentRegimeEffectiveness: { ALL: 0.95 } },
  { id: 'OPS-62', name: 'Compliance/Audit Agent', role: 'Immutable event logging, risk rule compliance, and regulatory audit', category: 'OPERATIONS', reputationScore: 99, calibrationScore: 0.99, winRateContribution: 64.0, pnlContributionUsd: 22.0, status: 'ACTIVE', currentRegimeEffectiveness: { ALL: 0.99 } },
];
